### ISSUE TITLE
Parts List

### ISSUE THREAD

**Issue by ptf569** [punk-security/bsides-cheltenham-2023-badge#2]
Hey guys, buzzing after the conf and really want to make the badge with by son.

Could you throw up some links for the parts needed please.

Thanks

PTF

**Comment by SimonGurney** [comment]
I'll get the list properly updated tomorrow as well as adding the eagle files in case you want to make your own version :)

For now, here is the part list from digikey.

If anyone wants a bag of components then DM me at simon@punksecurity.co.uk and I'll put a bulk order in and get them posted out in a week or two.  Same deal, donate £10 to mind.org.uk and send us proof.

 ![Screenshot_20230604-174127.png](https://github.com/punk-security/bsides-cheltenham-2023-badge/assets/22961341/c7dac253-876f-417e-a988-39a35635a560)
